explore_node:
  ros__parameters:
    use_sim_time: true
    robot_base_frame: base_link
    costmap_topic: /map
    costmap_updates_topic: /map_updates
    return_to_init: false
    visualize: true
    planner_frequency: 1.5
    progress_timeout: 50.0
    potential_scale: 25.0
    gain_scale: 2.0
    orientation_scale: 20.0
    goal_identity_tolerance: 0.5
    commitment_scale: 2.5
    commitment_hysteresis: 4.0
    commitment_max: 8.0
    transform_tolerance: 0.3
    min_frontier_size: 2.0
